### ISSUE TITLE
How to create a peripheral?

### ISSUE THREAD

**Issue by alexcastillo** [chrvadala/node-ble#17]
Thank you so much for this project!

I was wondering if it is possible to create a ble peripheral that can advertise some static data?

Something similar to [bleno](https://github.com/abandonware/bleno)'s example.

```js
bleno.startAdvertising(name, serviceUuids[, callback(error)]);

// or

bleno.startAdvertisingIBeacon(uuid, major, minor, measuredPower[, callback(error)]);
```

**Comment by chrvadala** [comment]
Hi @alexcastillo,
this capability it isn't still available, but might be added in a future version.

**Comment by alexcastillo** [comment]
Good to know, @chrvadala.

Thank you for the update, and keep up the good work!

**Comment by SimonGAndrews** [comment]
![AdvertCreation01](https://user-images.githubusercontent.com/55559464/103642825-9ff97780-4f4b-11eb-9f0c-c489f9025d36.jpg)

Ive got a project WIP that may help this along, happy to share as I go.  

the project is an 'Alexa Gadget'  based on raspberry pi, with Node.js  

Will publish on github eventually.  Here is notes on advertising with dbus-next and bluez.  Im having to learn alot as I go on the whole stack here so its taking a while.

**Comment by alexcastillo** [comment]
@SimonGAndrews,

This is awesome! Thank you so much for sharing.

I'll be happy to be one of your first testers once your publish your server GATT service.

Please keep me posted.
