### ISSUE TITLE
no avaliable adapter found 

### ISSUE THREAD

**Issue by EsraaAlaaOmar** [chrvadala/node-ble#21]
![image](https://user-images.githubusercontent.com/60965189/106014041-bcf61600-60c5-11eb-938d-355e28f9d42b.png)
 
I want to get the connected bluetooth adapter name from my phone  local host but I get "no available adapter found "

**Comment by chrvadala** [comment]
Do you have a bluez compliant device?
I suggest you to check the device with 
```
hcitool dev
```
