### ISSUE TITLE
"noble: unknown peripheral c44f3371766b, 183b, 2aa1 read!" Characteristics

### ISSUE THREAD

**Issue by TIB28** [chrvadala/node-ble#24]
hello ,
I have trouble , i try to get characteristics from my BLE sensor:
`const characteristicMagneticFlux = await peripheral.discoverSomeServicesAndCharacteristicsAsync(['183b'], ['2aa1']);`

but when i add an other characteristics like this :
`const characteristics2 = await peripheral.discoverSomeServicesAndCharacteristicsAsync(['183b'], ['2a19']);`

I have an error like this 

`noble: unknown peripheral c44f3371766b, 183b, 2aa1 read!
  noble: unknown peripheral c44f3371766b, 183b, 2aa1 read!`

Thanks for helping me.

**Comment by chrvadala** [comment]
I think that you posted on the wrong repo. This isn't noble project, but node-ble. 
https://github.com/noble/noble/blob/c4cd18a7a429bb832f6c4ca793be3faf9af884e9/lib/noble.js#L47
