### ISSUE TITLE
Device dbus "match" leak

### ISSUE THREAD

**Issue by tuxedoxt** [chrvadala/node-ble#36]
Hello,

using `Device.getDevice` repeatedly causes registered dbus "matches" to accumulate. I traced it until  that `_removeMatch` (dbus-next) triggers on event listener removal but doesn't really send the `RemoveMatch` message. Now not sure if this is a bug of this library or of `dbus-next` or if there's a version solving it.

This is one of two issues I noticed while repeatedly trying to enumerate a devices and read some properties from them (in a heavy BLE traffic area).

**Comment by ChocolateLoverRaj** [comment]
I got an error because of this leak. I started discovery and called `getDevices()` every second. After a few seconds I got this error:
```
DBusError: Connection ":1.45" is not allowed to add more match rules (increase limits in configuration file if required; max_match_rules_per_connection=512)
```

**Comment by ChocolateLoverRaj** [comment]
> Device.getDevice

Do you mean `Adapter.getDevice`?
