### ISSUE TITLE
Compatibility not specified

### ISSUE THREAD

**Issue by alakifan** [chrvadala/node-ble#51]
I had to dig through the closed issues tab to find out that this library is incompatible with windows, this should be specified on the readme to prevent people from wasting their morning like I did

**Comment by mxc42** [comment]
The readme does state this uses bluez (a Linux only utility), and links the compatible platforms and distributions. Sorry for the wasted morning though, that's always the worst.
[Readme Compatibility](https://github.com/chrvadala/node-ble#compatibility)

**Comment by Hypenexy** [comment]
Linux should at least be at tags or somewhere in the start not after I've already attempted to try an example!

**Comment by gmacario** [comment]
> Linux should at least be at tags or somewhere in the start not after I've already attempted to try an example!

Well I read on section "Compatibility" of the top-level README.md:

> This library works on many architectures supported by Linux.
