### ISSUE TITLE
How to get device name?

### ISSUE THREAD

**Issue by DrCWO** [chrvadala/node-ble#58]
I experimented a bit and knowing the UUID of the device I can work with it.
As I found I can get the list of the UUIDs of the discovered devices.

How can I find out the name of the device belonging to the UUID?
Background: I like to connect to a special device who's name I will know but not its UUID.

A hint would be appreciated.

Thanks DrCWO

**Comment by chrvadala** [comment]
With this method you can get the device name https://github.com/chrvadala/node-ble/blob/main/docs/api.md#Device+getName
