### ISSUE TITLE
LEAdvertisingManager1 not implemented?

### ISSUE THREAD

**Issue by ArcadeMachinist** [chrvadala/node-ble#60]
Should be pretty straightforward.
https://kernel.googlesource.com/pub/scm/bluetooth/bluez/+/5.50/doc/advertising-api.txt
I would do implementation for my own project, but my code is usually not neat and clean enough for pulls.

Some BLE lights I have do expect commands as an advertisment with manufacturer-specific data.

**Comment by chrvadala** [comment]
Currently this library can't support Peripheral mode
