### ISSUE TITLE
Get advertising data

### ISSUE THREAD

**Issue by Pantek59** [chrvadala/node-ble#66]
Hi

I couldn't find any way to get access to the advertising data sent out by a device. It's the service data, I am especially interested in, but manufacturer data would be nice, as well.

I was looking for something like `Device.getAdvertisingData()`, but if there is a way to achieve this, please educate a fool. :-)

EDIT: I just noticed that pull request https://github.com/chrvadala/node-ble/pull/61 might address my problem.

**Comment by chrvadala** [comment]
#61  has been released
