### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by aileenscott0101** [chrvadala/node-ble#7]
Hi folks,

I hope you don’t mind, we were testing out our security automation tool and ran it against your project.  A few issues came out that you may want to check out - we weren’t sure how to submit a PDF here, so we uploaded it to https://source-security.co.uk/579d0811-c72e-4788-a1a8-51dc79879054/ if you wanna check it out.

Any issues or feedback, just let us know.

Aileen

**Comment by chrvadala** [comment]
SPAM! DO NOT OPEN ATTACHED LINK
